### ISSUE TITLE
API endpoint "/get_columns" does not return all the columns

### ISSUE THREAD

**Issue by QuentinMacheda** [Group-3-Charlie/Backend#6]
### API endpoint "/get_columns" does not return all the columns, but only a few of them :

Columns retrieved :
![image](https://github.com/Group-3-Charlie/Backend/assets/69113642/5febb549-7084-4742-80e1-cdb9dd2fdee6)

Columns expected : 
State | Sex | GeneralHealth | PhysicalHealthDays | MentalHealthDays | LastCheckupTime | PhysicalActivities | SleepHours | RemovedTeeth | HadHeartAttack | HadAngina | HadStroke | HadAsthma | HadSkinCancer | HadCOPD | HadDepressiveDisorder | HadKidneyDisease | HadArthritis | HadDiabetes | DeafOrHardOfHearing | BlindOrVisionDifficulty | DifficultyConcentrating | DifficultyWalking | DifficultyDressingBathing | DifficultyErrands | SmokerStatus | ECigaretteUsage | ChestScan | RaceEthnicityCategory | AgeCategory | HeightInMeters | WeightInKilograms | BMI | AlcoholDrinkers | HIVTesting | FluVaxLast12 | PneumoVaxEver | TetanusLast10Tdap | HighRiskLastYear | CovidPos

**Comment by MrArnaudMichel** [comment]
The problem is still alive?

**Comment by QuentinMacheda** [comment]
Yes, it is ! Maybe this comes only with the .csv file that I upload most of the time...

**Comment by MrArnaudMichel** [comment]
#10
